<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Log In</name>
   <tag></tag>
   <elementGuidId>f25e450a-e404-4241-99ff-0b4ef232156e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='global-user-trigger']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#global-user-trigger</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>edd0aedc-f669-4550-ad3b-8d74408c5fdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>6b0d7186-ffd8-4290-abf1-e0306fffbe3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>global-user-trigger</value>
      <webElementGuid>14525ee0-5214-4e14-9acf-7dae6f60aded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-route</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4f244776-cac3-46db-b3b2-761b7cd61563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log In</value>
      <webElementGuid>3eae75fc-580f-4263-b5ea-684fdea92224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;global-user-trigger&quot;)</value>
      <webElementGuid>969a3690-c54a-469d-a296-7c221e7396d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='global-user-trigger']</value>
      <webElementGuid>3dddf3f3-135b-41b8-8f97-665d292c22e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='global-header']/div[2]/ul/li[2]/a</value>
      <webElementGuid>2a10f7b8-567e-4de0-833a-2571b46c8cb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Log In')]</value>
      <webElementGuid>5c6ab85f-d0dc-44ca-a53d-4357e0feea45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[2]/following::a[1]</value>
      <webElementGuid>0c103c98-76a0-4a43-b7c8-4e00f260fabf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ESPN'])[2]/following::a[2]</value>
      <webElementGuid>207d8e87-ea30-4ef2-9e3c-d5f5a2673995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome!'])[1]/preceding::a[1]</value>
      <webElementGuid>ae270e73-0910-4635-a123-abf9b4bb5fc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage my:'])[1]/preceding::a[1]</value>
      <webElementGuid>8eb9fd30-7bd6-4710-867f-34f6d4b6bdf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Log In']/parent::*</value>
      <webElementGuid>43371c53-8847-418a-aa1d-e6ce5690f1b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[47]</value>
      <webElementGuid>c187dc44-bc6e-4a6c-a638-213e81fbb58b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div[2]/ul/li[2]/a</value>
      <webElementGuid>6b11e2b9-9858-4de5-a198-4dc98a9517a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'global-user-trigger' and (text() = 'Log In' or . = 'Log In')]</value>
      <webElementGuid>b5435abe-271b-4de8-8a99-086e8c33ecfd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
