<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Log In_1 (1)</name>
   <tag></tag>
   <elementGuidId>370577b0-bda1-4e12-beab-61df5bdfcb57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='global-viewport']/div[3]/div/ul/li[7]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#global-viewport > div.global-user > div.global-user-container > ul.account-management > li:nth-of-type(7) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7128835a-fbbf-46ec-a9fd-99021c830e65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-affiliatename</name>
      <type>Main</type>
      <value>espn</value>
      <webElementGuid>732cb79a-fcf9-4f25-a484-549526d3523c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-language</name>
      <type>Main</type>
      <value>en</value>
      <webElementGuid>e68c3504-b790-4616-b9e5-00f7b14af423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-regformid</name>
      <type>Main</type>
      <value>espn</value>
      <webElementGuid>e272c952-9175-46d5-89f8-6441a8e675f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tref</name>
      <type>Main</type>
      <value>/members/v3_1/login</value>
      <webElementGuid>bdb2a96b-51d9-4d0a-8b1d-6074fd1334dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-behavior</name>
      <type>Main</type>
      <value>overlay</value>
      <webElementGuid>f29667a0-26c8-4c1c-a644-fbc54139c5f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-route</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>06635f1a-5573-49d7-8965-dea7fd9ec80e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>a8e0edb5-c4f8-4b6b-88f6-77b41bce1c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log In</value>
      <webElementGuid>f4e76819-dc62-407d-af86-e9a295968094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;global-viewport&quot;)/div[@class=&quot;global-user&quot;]/div[@class=&quot;global-user-container&quot;]/ul[@class=&quot;account-management&quot;]/li[7]/a[1]</value>
      <webElementGuid>a0c5fe79-5e25-4c52-98e5-d82836d4cd56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='global-viewport']/div[3]/div/ul/li[7]/a</value>
      <webElementGuid>885708f5-1b34-4cf5-8628-e3c3c9976599</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Log In')])[3]</value>
      <webElementGuid>81c5f045-51f0-4c67-9b1d-7af57c8e2c8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Video Settings'])[2]/following::a[1]</value>
      <webElementGuid>c0486c75-1587-4622-a992-49bd55ba4bce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TV Provider'])[2]/following::a[2]</value>
      <webElementGuid>6d655b2c-2c3a-4cf2-b1b7-45f930892a39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[2]/preceding::a[1]</value>
      <webElementGuid>8c69db0d-3439-4b45-b724-dc9169b74507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[53]</value>
      <webElementGuid>cf304881-4a03-4c60-a5ec-eda8aa048858</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/ul/li[7]/a</value>
      <webElementGuid>91fd237a-beae-461d-80a2-e02ca13cdc46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Log In' or . = 'Log In')]</value>
      <webElementGuid>6ffaf280-db55-408a-b90d-40e49c181eee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
