<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Disney accountFind Your AccountTell us _600c86</name>
   <tag></tag>
   <elementGuidId>7f757eae-b2b3-483e-a9f3-7705a856c779</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e6dda92d-a423-47d2-964f-bb4565ac6e5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loading-container </value>
      <webElementGuid>32f9655e-6112-48f5-8d84-6a29731696ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Disney accountFind Your AccountTell us your email address or username and we'll get you signed in.Email or UsernameContinueCancelStill having trouble?Visit ESPN Support</value>
      <webElementGuid>1c09bfd7-6c91-4a6c-b6a6-71be295d5ae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[3]/div[@class=&quot;loading-container&quot;]</value>
      <webElementGuid>aceb03f9-0efb-4051-aa06-a3a9fece9b89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TestCase004/Page_ESPN - Serving Sports Fans. Anytime. Anywhere/iframe_concat(id(, , oneid-iframe, , ))_one_8d9a57</value>
      <webElementGuid>abb239ec-a0ee-4912-abb6-650bb0a9f582</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div</value>
      <webElementGuid>39657df6-6683-4dd4-a65f-6d1484834230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div</value>
      <webElementGuid>caa7b3a3-0747-40cb-ab2f-e0e10c6d3c03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;Disney accountFind Your AccountTell us your email address or username and we&quot; , &quot;'&quot; , &quot;ll get you signed in.Email or UsernameContinueCancelStill having trouble?Visit ESPN Support&quot;) or . = concat(&quot;Disney accountFind Your AccountTell us your email address or username and we&quot; , &quot;'&quot; , &quot;ll get you signed in.Email or UsernameContinueCancelStill having trouble?Visit ESPN Support&quot;))]</value>
      <webElementGuid>5e1a56f3-1a96-4fea-8174-7c5ef0ffb465</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
