<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_Disney accountFind Your AccountTell us_7d549b</name>
   <tag></tag>
   <elementGuidId>aae3b292-b9b2-4434-a4e9-12278ad15faa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div/div/form</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>form.form-section.otp-prompt-login-value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>c0b6904c-e3a9-4e3b-ab01-ba562e88ef86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-section otp-prompt-login-value</value>
      <webElementGuid>455d9ffd-a8e6-43e7-8cac-9de3e0c06097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Disney accountFind Your AccountTell us your email address or username and we'll get you signed in.Email or UsernameContinueCancelStill having trouble?Visit ESPN Support</value>
      <webElementGuid>2ae50c1a-7a6a-4134-8df0-22e3286c11ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[3]/div[@class=&quot;loading-container&quot;]/div[@class=&quot;view view-starry-night&quot;]/form[@class=&quot;form-section otp-prompt-login-value&quot;]</value>
      <webElementGuid>e0410417-dbf9-4222-a0ab-1d1f4c1c1b31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TestCase004/Page_ESPN - Serving Sports Fans. Anytime. Anywhere/iframe_concat(id(, , oneid-iframe, , ))_one_8d9a57</value>
      <webElementGuid>4023b885-4bc2-4caf-8abf-dec844fabd79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div/form</value>
      <webElementGuid>0b1cceec-ee52-4377-9b18-caf7d4d31f42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>4d649ec0-f23a-4eea-89b9-e27ec653002f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[(text() = concat(&quot;Disney accountFind Your AccountTell us your email address or username and we&quot; , &quot;'&quot; , &quot;ll get you signed in.Email or UsernameContinueCancelStill having trouble?Visit ESPN Support&quot;) or . = concat(&quot;Disney accountFind Your AccountTell us your email address or username and we&quot; , &quot;'&quot; , &quot;ll get you signed in.Email or UsernameContinueCancelStill having trouble?Visit ESPN Support&quot;))]</value>
      <webElementGuid>a274cf44-6759-4735-92d6-2ba3cbab48f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
