<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Log In_1</name>
   <tag></tag>
   <elementGuidId>3798a257-ce08-4f18-b38b-e111f0dd5ff0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='global-viewport']/div[3]/div/ul/li[7]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#global-viewport > div.global-user > div.global-user-container > ul.account-management > li:nth-of-type(7) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>506be610-fde5-4876-996a-5ce1b3988a5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-affiliatename</name>
      <type>Main</type>
      <value>espn</value>
      <webElementGuid>cfcff103-a093-4270-bcb2-416ba4aece79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-language</name>
      <type>Main</type>
      <value>en</value>
      <webElementGuid>fea1d67d-794d-4721-819d-eb0bb5697c77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-regformid</name>
      <type>Main</type>
      <value>espn</value>
      <webElementGuid>ea667d05-94ee-4457-9910-af0e4bcf8131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tref</name>
      <type>Main</type>
      <value>/members/v3_1/login</value>
      <webElementGuid>084395e1-6019-4104-9056-ede7199da684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-behavior</name>
      <type>Main</type>
      <value>overlay</value>
      <webElementGuid>2b84b6bf-9c1c-401a-a16b-bd460886633d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-route</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e1449474-3f8f-42f0-b3a3-e5df9b7f5374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>1dedff92-1d20-4c21-99ff-846db8dfb141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log In</value>
      <webElementGuid>aa98ec80-e3f6-485e-8594-3b23c87755a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;global-viewport&quot;)/div[@class=&quot;global-user&quot;]/div[@class=&quot;global-user-container&quot;]/ul[@class=&quot;account-management&quot;]/li[7]/a[1]</value>
      <webElementGuid>2a0d8c3d-378c-4499-8111-8deb1f719d6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='global-viewport']/div[3]/div/ul/li[7]/a</value>
      <webElementGuid>1733dd8d-4d55-4152-b7fb-5d09bc63f829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Log In')])[3]</value>
      <webElementGuid>83ef38f4-9130-43a1-9526-2cb486ec35d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Video Settings'])[2]/following::a[1]</value>
      <webElementGuid>e7f98dd7-fae3-49f4-aae4-90896c8ba10d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TV Provider'])[2]/following::a[2]</value>
      <webElementGuid>152be4d3-7313-49f2-b4a1-dda8cc371c48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[2]/preceding::a[1]</value>
      <webElementGuid>d14abfe5-2b0b-4a18-9c11-e907052cd30b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[53]</value>
      <webElementGuid>300fae52-200a-4c1f-9dd6-8bdd858a6e7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/ul/li[7]/a</value>
      <webElementGuid>416eaab9-3e21-4727-acdf-fdd77c808c2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Log In' or . = 'Log In')]</value>
      <webElementGuid>c74843b2-e005-42cb-b4dd-7f5893944e3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
