<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , oneid-iframe, , ))_one_8d9a57</name>
   <tag></tag>
   <elementGuidId>ded053aa-2413-4ac5-9796-fcee53d4b31c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='oneid-iframe']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#oneid-iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>29304061-d99c-49b7-b474-042d2edf0c14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>oneid-iframe</value>
      <webElementGuid>20797f1d-f3ef-4d73-885c-32ea152905bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>oneid-iframe</value>
      <webElementGuid>08f927fc-36fc-475f-9080-1c90aa7b8907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c152e85b-4cfd-4ef2-98f4-1b83c4f8787f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Account</value>
      <webElementGuid>7b00acc5-1b2f-4a32-966a-bd269e200d24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn.registerdisney.go.com/v4/bundle/web/ESPN-ONESITE.WEB/en-US?cssOverride=https%3A%2F%2Fsecure.espncdn.com%2Fcombiner%2Fc%3Fcss%3Ddisneyid%2Fcore.css&amp;logLevel=INFO</value>
      <webElementGuid>84d67ffa-c6b3-4d78-9c8c-0f25fa03b615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;oneid-iframe&quot;)</value>
      <webElementGuid>1c1ab0e7-1f56-49e9-bc2e-332ab3a8dab0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='oneid-iframe']</value>
      <webElementGuid>06ac2024-3392-42c7-a101-2c6fa046b3a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='oneid-wrapper']/iframe</value>
      <webElementGuid>1c746118-d742-4d36-b196-62f0487b5859</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/iframe</value>
      <webElementGuid>f1035f04-a2a9-43d3-98dd-f23ff064b35e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'oneid-iframe' and @name = 'oneid-iframe' and @title = 'Account' and @src = 'https://cdn.registerdisney.go.com/v4/bundle/web/ESPN-ONESITE.WEB/en-US?cssOverride=https%3A%2F%2Fsecure.espncdn.com%2Fcombiner%2Fc%3Fcss%3Ddisneyid%2Fcore.css&amp;logLevel=INFO']</value>
      <webElementGuid>51b4b9a0-bbfc-4a44-92e1-cfe578de428b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
