<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Log In_1</name>
   <tag></tag>
   <elementGuidId>28f71ca8-c5f2-419a-b799-14d1f1dd007c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='global-viewport']/div[3]/div/ul/li[7]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#global-viewport > div.global-user > div.global-user-container > ul.account-management > li:nth-of-type(7) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>87c88bc2-d146-48bf-bbb4-5f628cc7978f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-affiliatename</name>
      <type>Main</type>
      <value>espn</value>
      <webElementGuid>e47a251d-2209-4912-b606-d4aa39e2f499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-language</name>
      <type>Main</type>
      <value>en</value>
      <webElementGuid>b0f73719-ed21-471e-b416-de51c6bfeb02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-regformid</name>
      <type>Main</type>
      <value>espn</value>
      <webElementGuid>268d2491-3654-4455-b059-13864ce4e1b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tref</name>
      <type>Main</type>
      <value>/members/v3_1/login</value>
      <webElementGuid>bdb353f4-83e1-4d74-affc-4e6519a8a632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-behavior</name>
      <type>Main</type>
      <value>overlay</value>
      <webElementGuid>0ce72f3a-c18c-46f1-8489-decd2524848b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-route</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6c92642a-069c-4dba-87d8-35fc9bfac1e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>a0ed21de-00e6-453c-83d7-d7784d7c87b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log In</value>
      <webElementGuid>25902b60-40cf-421b-ad7e-46447294e619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;global-viewport&quot;)/div[@class=&quot;global-user&quot;]/div[@class=&quot;global-user-container&quot;]/ul[@class=&quot;account-management&quot;]/li[7]/a[1]</value>
      <webElementGuid>fa844b28-a6dd-4bc2-a6fa-5662b5d943d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='global-viewport']/div[3]/div/ul/li[7]/a</value>
      <webElementGuid>d2ea8534-cf20-44e3-a743-a00e9e3fba2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Log In')])[3]</value>
      <webElementGuid>1cfb33c7-5726-40d2-951a-1cba58afa8a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Video Settings'])[2]/following::a[1]</value>
      <webElementGuid>52bd76b2-e0b1-4201-9521-8cd0fa21d2f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TV Provider'])[2]/following::a[2]</value>
      <webElementGuid>7d2597b0-9708-49c1-9cd3-dd35fc3012cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[2]/preceding::a[1]</value>
      <webElementGuid>bc40d86c-edba-4029-ad80-fcb74c12ae51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[53]</value>
      <webElementGuid>696ca2f3-a3d2-4144-b948-86e843e43503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/ul/li[7]/a</value>
      <webElementGuid>5378ff6b-52f7-4cfe-9be7-1efa7d355060</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Log In' or . = 'Log In')]</value>
      <webElementGuid>4f7982a8-9d5b-4419-a9a0-5a87f031412f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
