<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sign Up</name>
   <tag></tag>
   <elementGuidId>4bac62f2-37d1-442e-b37d-6c3ac629ec26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='BtnCreateAccount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BtnCreateAccount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4b94497d-d426-497a-8947-db76ce8e7ae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>bc6388b3-9663-4c48-9201-e520f1f2797e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary</value>
      <webElementGuid>f03b8024-0321-43d6-ac1e-f944d1fb0475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BtnCreateAccount</value>
      <webElementGuid>303c2a35-1709-45fc-9979-cd03951f045d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>BtnCreateAccount</value>
      <webElementGuid>6b7dbcb8-bb5a-4d5b-8b4e-ed9236af7f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign Up</value>
      <webElementGuid>dbf03fdb-9113-4bf3-b939-0d596adefb46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BtnCreateAccount&quot;)</value>
      <webElementGuid>50c7b885-4b8e-4410-9b2b-5923e7d0d2c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TestCase010/Page_ESPN - Serving Sports Fans. Anytime. Anywhere/iframe_concat(id(, , oneid-iframe, , ))_one_8d9a57</value>
      <webElementGuid>c3498f97-173b-496c-89d1-01358452fb46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='BtnCreateAccount']</value>
      <webElementGuid>a0200620-8b25-4133-a766-f5b48aac0b40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div/form/button</value>
      <webElementGuid>7fa230b2-c0c4-464c-b7e6-918a5527cfeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log In'])[2]/following::button[1]</value>
      <webElementGuid>256351a0-47f3-4ae4-bee7-f7a79a18302e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password (case sensitive)'])[1]/following::button[2]</value>
      <webElementGuid>fa0c4c8b-346d-4b9f-bf74-d3e28cc80492</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'BtnCreateAccount', '&quot;', ')')])[1]/preceding::button[2]</value>
      <webElementGuid>b6607105-6b13-4d55-8641-79e789ada0a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign Up']/parent::*</value>
      <webElementGuid>e349d1f7-be07-4b3a-90c5-97f5991d4b9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>77034339-08cb-4deb-a11d-672195ed3af6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'BtnCreateAccount' and (text() = 'Sign Up' or . = 'Sign Up')]</value>
      <webElementGuid>d8eb89dc-833c-496b-a029-a7347f155d18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
