<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_Disney accountCreate AccountFirst Name_f26279</name>
   <tag></tag>
   <elementGuidId>c952ff84-6731-4308-bbb9-d017b5ac0b71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div/div/form</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>form.form-section.registration</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>679d1f17-d872-40ee-a1d6-cb660dcc5527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-section registration</value>
      <webElementGuid>e296dca7-18b9-44a5-a6cf-34c4f97eacca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Disney accountCreate AccountFirst NameLast NameEmail AddressIt looks like that email has already been used to create an account at Disney, ESPN, Marvel, or ABC. If this is your email address, just log in to your account. Password (case sensitive) Enter at least 6 characters.Don't use the password from another account.Use letters together with spaces, numbers, or symbols (!@#$%^&amp;*). Show passwordPlease send me occasional information and offers about my favorite teams, sports and other information from:ESPN, ESPN+ and The Walt Disney Family of CompaniesBy creating an account, you agree to our Terms of Use and acknowledge that you have read our Privacy Policy and US State Privacy Rights Notice.My home country/region: United States. Change.Sign UpAlready have an account? Log In</value>
      <webElementGuid>d917448e-0d58-45d5-ae4f-6a460122a6c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[3]/div[@class=&quot;loading-container&quot;]/div[@class=&quot;view view-starry-night&quot;]/form[@class=&quot;form-section registration&quot;]</value>
      <webElementGuid>07fe2bed-f680-449d-9e5f-4a0076226e6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TestCase009/Page_ESPN - Serving Sports Fans. Anytime. Anywhere/iframe_concat(id(, , oneid-iframe, , ))_one_8d9a57</value>
      <webElementGuid>af242cbc-775a-44d1-a6c7-2f975d6ec78d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div/form</value>
      <webElementGuid>ec59606b-c60e-414b-813e-1abfa6672216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>fad1c734-d3b9-42ec-bd6a-b0ddf658ed90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[(text() = concat(&quot;Disney accountCreate AccountFirst NameLast NameEmail AddressIt looks like that email has already been used to create an account at Disney, ESPN, Marvel, or ABC. If this is your email address, just log in to your account. Password (case sensitive) Enter at least 6 characters.Don&quot; , &quot;'&quot; , &quot;t use the password from another account.Use letters together with spaces, numbers, or symbols (!@#$%^&amp;*). Show passwordPlease send me occasional information and offers about my favorite teams, sports and other information from:ESPN, ESPN+ and The Walt Disney Family of CompaniesBy creating an account, you agree to our Terms of Use and acknowledge that you have read our Privacy Policy and US State Privacy Rights Notice.My home country/region: United States. Change.Sign UpAlready have an account? Log In&quot;) or . = concat(&quot;Disney accountCreate AccountFirst NameLast NameEmail AddressIt looks like that email has already been used to create an account at Disney, ESPN, Marvel, or ABC. If this is your email address, just log in to your account. Password (case sensitive) Enter at least 6 characters.Don&quot; , &quot;'&quot; , &quot;t use the password from another account.Use letters together with spaces, numbers, or symbols (!@#$%^&amp;*). Show passwordPlease send me occasional information and offers about my favorite teams, sports and other information from:ESPN, ESPN+ and The Walt Disney Family of CompaniesBy creating an account, you agree to our Terms of Use and acknowledge that you have read our Privacy Policy and US State Privacy Rights Notice.My home country/region: United States. Change.Sign UpAlready have an account? Log In&quot;))]</value>
      <webElementGuid>f7d2ef1d-e0b0-426f-8e85-a46c335728be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
