<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_My home countryregion Canada. Change</name>
   <tag></tag>
   <elementGuidId>5cf417f1-98e7-4e9c-b6f0-b8add1c7839f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='UpdateLegalCountry']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#UpdateLegalCountry</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>94886570-03bd-4afa-8d49-0aa785d149b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>legal-locale</value>
      <webElementGuid>3c4bb567-505b-4f9c-b389-3e6c3324f349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UpdateLegalCountry</value>
      <webElementGuid>1206cf0b-d1a6-40fe-88b4-b3b1ff436835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>UpdateLegalCountry</value>
      <webElementGuid>5456c81f-cef0-48c2-ab99-a9b483df9550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My home country/region: Canada. Change.</value>
      <webElementGuid>649dee70-f9f1-4c2d-a0ea-f7d0a0e1b06c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UpdateLegalCountry&quot;)</value>
      <webElementGuid>521b7041-cff3-4d0a-8d33-541d9598bef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TestCase009/Page_ESPN - Serving Sports Fans. Anytime. Anywhere/iframe_concat(id(, , oneid-iframe, , ))_one_8d9a57</value>
      <webElementGuid>9c2f7863-9405-4877-a7e3-45873c15235e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='UpdateLegalCountry']</value>
      <webElementGuid>e92a2a58-b070-4e8e-bccc-edc243ce9230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div/form/p[3]</value>
      <webElementGuid>1a905e28-768d-42e6-82c1-42b0f075a706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy'])[1]/following::p[1]</value>
      <webElementGuid>01e89d58-9874-4a98-82f4-308dc46e2f36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms of Use'])[1]/following::p[1]</value>
      <webElementGuid>1dd94ce6-d51b-4d05-a989-8722b12b41c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Up'])[1]/preceding::p[1]</value>
      <webElementGuid>fbdfbe5f-2ba0-41f7-bc9b-2143e9aa2b55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'UpdateLegalCountry', '&quot;', ')')])[1]/preceding::p[2]</value>
      <webElementGuid>3b501f13-d7a7-41c4-adbc-10fe3881737a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='My home country/region: Canada.']/parent::*</value>
      <webElementGuid>6c4926b6-d0d6-4dbe-a2db-78cd959773ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[3]</value>
      <webElementGuid>f1dd2164-022e-4a0f-9abe-cfd998491f90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'UpdateLegalCountry' and (text() = 'My home country/region: Canada. Change.' or . = 'My home country/region: Canada. Change.')]</value>
      <webElementGuid>5c330684-f110-4005-8efb-f0716f64917c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
